version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "8081:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"  
